server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/owasp
    username: root
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
